Resources:
  MastersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.mastersTable}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
